### ISSUE TITLE
Microsoft Graph service exception - Max page size should be <= 501

### ISSUE THREAD

**Issue by roldengarm** [pnp/pnpassessment#57]
I'm trying to run the ACS Assessment using interactive auth. I've created the App Reg as documented.
When running the assessment with:

```
microsoft365-assessment.exe start --mode AddInsACS --authmode interactive --tenant tenant.sharepoint.com --applicationid 1234...
```
I get: Assessment job not started due to error: Microsoft Graph service exception

In the logs, I see below:
```
2024-05-22 10:54:30.134 +12:00 [INF] Sending HTTP request POST https://graph.microsoft.com/v1.0/search/query
2024-05-22 10:54:30.189 +12:00 [INF] Received HTTP response headers after 54.34ms - 400
2024-05-22 10:54:30.189 +12:00 [INF] End processing HTTP request after 54.5618ms - 400
2024-05-22 10:54:30.189 +12:00 [ERR] Error starting assessment job: Microsoft Graph service exception
HttpResponseCode: 400
Code: BadRequest
Message: SearchRequest Invalid (Max page size should be <= 501.)
ClientRequestId: 
target: 
details: [{"code":"Microsoft.SubstrateSearch.Api.ErrorReporting.ResourceBasedExceptions.BadRequestException","message":"Max page size should be <= 501.","target":"","httpCode":400}]
httpCode: 400

PnP.Core.MicrosoftGraphServiceException: Microsoft Graph service exception
   at PnP.Core.Services.BatchClient.ExecuteMicrosoftGraphInteractiveAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteMicrosoftGraphBatchAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
   at PnP.Core.Model.BaseDataModel`1.RequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
   at PnP.Core.Model.BaseDataModel`1.RawRequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
   at PnP.Core.Admin.Model.SharePoint.SiteCollectionEnumerator.GetViaGraphSearchApiAsync(PnPContext context, VanityUrlOptions vanityUrlOptions, SiteCollectionFilter filter, Int32 pageSize)
   at PnP.Core.Admin.Model.SharePoint.SiteCollectionEnumerator.GetAsync(PnPContext context, VanityUrlOptions vanityUrlOptions, Boolean ignoreUserIsTenantAdmin, SiteCollectionFilter filter)
   at PnP.Core.Admin.Model.SharePoint.SiteCollectionManager.GetSiteCollectionsAsync(Boolean ignoreUserIsSharePointAdmin, SiteCollectionFilter filter, VanityUrlOptions vanityUrlOptions)
   at PnP.Scanning.Core.Services.SiteEnumerationManager.EnumerateSiteCollectionsToScanAsync(StartRequest start, AuthenticationManager authenticationManager, Action`1 feedback)
   at PnP.Scanning.Core.Services.Scanner.Start(StartRequest request, IServerStreamWriter`1 responseStream, ServerCallContext context)
2024-05-22 10:54:30.191 +12:00 [INF] Executed endpoint 'gRPC - /PnP.Scanning.Core.Services.PnPScanner/Start'
2024-05-22 10:54:30.191 +12:00 [INF] Request finished HTTP/2 POST http://localhost:25010/PnP.Scanning.Core.Services.PnPScanner/Start - 200 null application/grpc 1807.8774ms
````

**Comment by EddieDL** [comment]
This seems like a common issue. I would recommend the following changes be made:
1. Catch this error and provide a better explanation about what is really going on.
2. Update documentation to provide some more real description about what you should do if you have over 500 sites.

I ran into the same issue and am still trying to figure out the right thing to do to make it work.

**Comment by jansenbe** [comment]
@EddieDL : were you also use interactive auth? Depending on the auth model and whether you're a tenant admin or not different site enumeration models are used. I'll try to reproduce and fix.

@roldengarm : thx for raising this

**Comment by jansenbe** [comment]
@roldengarm  / @EddieDL : can you do a Fiddler trace while trying the above? In code we limit page size to 500, so something else must be going on. Please send the Fiddler trace to bjansen@microsoft.com.

FYI: also se https://github.com/pnp/pnpassessment/issues/39

**Comment by jansenbe** [comment]
@EddieDL : this issue has been fixed, thanks for the help :-) Will be included in the next release of the assessment tool

**Comment by ArturoAP** [comment]
> [@EddieDL](https://github.com/EddieDL) : this issue has been fixed, thanks for the help :-) Will be included in the next release of the assessment tool

Hi @jansenbe we've upgraded to latest version 1.9, however we are still facing this issue using Delegated permissions, are there additional details on Authentication mode, options or flags required to make it work?
